// Gray-Scott display pass -- Layer 4d.
//
// Reads the latest RGBA16F (u, v) state and produces an RGBA8 colour
// frame. v carries the pattern; we tint it with a two-stop gradient and
// add a subtle edge highlight from |laplacian(v)| so cell membranes
// read distinctly from interiors. The pattern itself is generated by
// pde_grayscott.frag, so this shader has no audio inputs (those are
// folded into the solver's F/k).
//
// Colour: smoothstep on v with a configurable A->B palette. Default
// (deep-purple -> warm-cream) gives the patterns a "biological" tone
// rather than the petri-dish-green that comes up in many GS demos.

#version 440

layout(location = 0) in  vec2 v_uv;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4  qt_Matrix;
    float qt_Opacity;
};

layout(std140, binding = 1) uniform dispBuf {
    vec4  colorA;        // background / low-v
    vec4  colorB;        // foreground / high-v
    float lowThr;        // smoothstep low
    float highThr;       // smoothstep high
    float edgeStrength;  // scales the Laplacian-based edge glow
    float gain;          // overall brightness multiplier
    vec2  invResolution; // 1 / (gridW, gridH) for neighbour offsets
};

layout(binding = 2) uniform sampler2D state;

void main()
{
    vec2 c = texture(state, v_uv).rg;
    float v = c.g;

    // Edge highlight via 5-point Laplacian on v. Same explicit-offset
    // pattern the solver uses (Qt's shader baker rejects textureOffset
    // for cross-target portability).
    vec2 dx = vec2(invResolution.x, 0.0);
    vec2 dy = vec2(0.0, invResolution.y);
    float lap =
          texture(state, v_uv + dx).g
        + texture(state, v_uv - dx).g
        + texture(state, v_uv + dy).g
        + texture(state, v_uv - dy).g
        - 4.0 * v;
    float edge = clamp(abs(lap) * 8.0, 0.0, 1.0);

    float t = smoothstep(lowThr, highThr, v);
    vec3 col = mix(colorA.rgb, colorB.rgb, t);
    col += vec3(0.45, 0.40, 0.55) * edge * edgeStrength;

    col *= gain;
    fragColor = vec4(col, 1.0);
}
